name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      SBI_ID: ${{ secrets.SBI_ID }}
      SBI_PASS: ${{ secrets.SBI_PASS }}
      GAS_URL: ${{ secrets.GAS_URL }}
      SLEEP_DURATION: ${{ secrets.SLEEP_DURATION }}

    steps:
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run
      run: cargo run --verbose
